name: donasiku
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  camera: ^0.10.5+9 
  path_provider: ^2.0.11
  path: ^1.8.2
  http: ^1.2.1 
  dotted_border: ^2.1.0   
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: "^0.14.4"

flutter_native_splash:
  color: "#ffffff"
  image: Assets/Logo-Donasiku.png
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "Assets/Logo-Donasiku.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"


flutter:
  uses-material-design: true
  
  assets:
    - Assets/
